#Application Configuration
server:
  port: 8087
spring:
  application:
    name: api-rest-products

config:
  base:
    enpoint:
      accounts: http://localhost:8082/api/accounts
      credits: http://localhost:8084/api/credit
      creditcards: http://localhost:8083/api/credit-card
      debitcards: http://localhost:8086/api/debit-card