#Application Configuration
server:
  port: 8083
spring:
  application:
    name: api-rest-credit-cards
  data:
    mongodb:
      uri: mongodb+srv://user:pass@cluster-demo.wjgme.mongodb.net/credit-cards-db
      port: 27017
      username: user
      password: pass
  cloud:
    config:
      enabled: false